### ISSUE TITLE
Hang when editing struct annotation

### ISSUE THREAD

**Issue by Wuvist** [textmate/thrift.tmbundle#4]
Hi, Thanks for this bundle.

I have been using this bundle to edit thrift file in sublime on mac for a while, it works like a charm, until I tried to edit thrift annotation, for example:

``` thrift
struct User {
    1: string ID
    2: string UserName (input = "rich")
    3: string Password
    4: string Name
}
```

copy & paste  (input = "rich") to some other file, select rich, press " to quote it extra, will result sublime text 2 to hang.

I'm not sure if this is the bundle's issue or sublime's or even mac's. but guess I just raise the here first.

**Comment by Wuvist** [comment]
Seems that the syntax rule about annotation in thrift struct is buggy, remove them:
https://gist.github.com/Wuvist/ee9766ff0a0fa3f32dc9

resolved the issue.

**Comment by infininight** [comment]
Not seeing an issue in TextMate, if anyone is seeing an issue in Textmate or knows of a fix for Sublime reopen this bug.
